/*
 * MathGame - a competitive math game
 * Copyright (C) 2015  saber2014
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

#ifndef ENUMS_H
#define ENUMS_H

enum CONSOLE_COLOR
{
	CONSOLE_COLOR_DEFAULT = -1,
	CONSOLE_COLOR_BLACK = 0,
	CONSOLE_COLOR_BLUE,
	CONSOLE_COLOR_GREEN,
	CONSOLE_COLOR_AQUA,
	CONSOLE_COLOR_RED,
	CONSOLE_COLOR_PURPLE,
	CONSOLE_COLOR_YELLOW,
	CONSOLE_COLOR_WHITE,
	CONSOLE_COLOR_GRAY,
	CONSOLE_COLOR_LIGHT_BLUE,
	CONSOLE_COLOR_LIGHT_GREEN,
	CONSOLE_COLOR_LIGHT_AQUA,
	CONSOLE_COLOR_LIGHT_RED,
	CONSOLE_COLOR_LIGHT_PURPLE,
	CONSOLE_COLOR_LIGHT_YELLOW,
	CONSOLE_COLOR_BRIGHT_WHITE
};

enum SCREEN_ALIGN
{
	SCREEN_ALIGN_DEFAULT = 0,
	SCREEN_ALIGN_LEFT = 1,
	SCREEN_ALIGN_HCENTER = 2,
	SCREEN_ALIGN_RIGHT = 4,
	SCREEN_ALIGN_TOP = 8,
	SCREEN_ALIGN_VCENTER = 16,
	SCREEN_ALIGN_BOTTOM = 32
};

enum SCREEN_MESSAGE_STYLE
{
	SCREEN_MESSAGE_STYLE_DEFAULT = -1,
	SCREEN_MESSAGE_STYLE_BLUE = 0,
	SCREEN_MESSAGE_STYLE_GREEN,
	SCREEN_MESSAGE_STYLE_AQUA,
	SCREEN_MESSAGE_STYLE_RED,
	SCREEN_MESSAGE_STYLE_PURPLE,
	SCREEN_MESSAGE_STYLE_YELLOW,
};

enum MANAGER_CALLBACK
{
	MANAGER_CALLBACK_DEFAULT = 0,
	MANAGER_CALLBACK_GAME_OVER
};

enum OBJECT_TYPE
{
	OBJECT_TYPE_NONE = 0,
	OBJECT_TYPE_PLAYER1,
	OBJECT_TYPE_PLAYER2,
	OBJECT_TYPE_NUMBER,
	OBJECT_TYPE_SHOT,
	OBJECT_TYPE_NUMBERS_EATER
};

enum OBJECT_MOVE
{
	OBJECT_MOVE_DEFAULT = 0,
	OBJECT_MOVE_UP = 1,
	OBJECT_MOVE_RIGHT,
	OBJECT_MOVE_DOWN,
	OBJECT_MOVE_LEFT
};

enum EXERCISE_TYPE
{
	EXERCISE_TYPE_DEFAULT = 0,
	EXERCISE_TYPE_SIMPLE,
	EXERCISE_TYPE_COMPLEX
};

enum EXERCISE_SIGN
{
	EXERCISE_SIGN_DEFAULT = 0,
	EXERCISE_SIGN_PLUS,
	EXERCISE_SIGN_MINUS,
	EXERCISE_SIGN_MULTIPLICATION,
	EXERCISE_SIGN_DIVISION
};

enum EXERCISE_HIDE
{
	EXERCISE_HIDE_DEFAULT = 0,
	EXERCISE_HIDE_NUMBER1,
	EXERCISE_HIDE_NUMBER2,
	EXERCISE_HIDE_NUMBER3,
	EXERCISE_HIDE_NUMBER4
};

enum MAIN_MENU_ITEM
{
	MAIN_MENU_ITEM_INSTRUCTIONS = 0,
	MAIN_MENU_ITEM_START_GAME,
	MAIN_MENU_ITEM_START_GAME_LEVEL,
	MAIN_MENU_ITEM_EXIT
};

enum PAUSE_MENU_ITEM
{
	PAUSE_MENU_ITEM_EXIT = 0,
	PAUSE_MENU_ITEM_BACK_MAIN_MENU,
	PAUSE_MENU_ITEM_CONTINUE_PLAY,
	PAUSE_MENU_ITEM_RESTART,
	PAUSE_MENU_ITEM_NEXT
};

#endif